config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end

  resources :posts, only: [:new, :create, :destroy, :edit, :update] do
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end

  resources :comments, only: [:destroy]
  resources :likes, only: [:destroy]

  namespace :api, defaults: { format: :json } do
    resources :posts, only: [:index] do
      resources :comments, only: [:create, :index]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    if user.admin?
      can :manage, :all
    else
      can %i[update destroy], Post, user: user
      can :destroy, Comment, user: user
      can %i[read create], :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :comments_counter

  def update_counter(value)
    post.update(comments_counter: value)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :likes_counter
  validates :user_id, uniqueness: { scope: :post_id }

  def update_counter(value)
    post.update(likes_counter: value)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true,
                    length: { maximum: 250, too_long: 'must not exceed 250 characters' }
  validates :comments_counter, :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :user, counter_cache: :posts_counter
  has_many :comments, dependent: :destroy
  has_many :likes, counter_cache: :likes_counter
  has_many :users, through: :likes, counter_cache: :likes_counter

  def recent_comments(limit = 5)
    comments.last limit
  end

  def liked?(id)
    users.exists? id
  end

  def update_counter(value)
    user.update posts_counter: value
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :jwt_authenticatable, jwt_revocation_strategy: self

  validates :name, :email, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes

  def admin?
    role == 'admin'
  end

  def recent_posts(limit = 3)
    posts.includes(:comments).order('created_at').last(limit)
  end
end

app/controllers/api/_comments_controller.rb
class Api::CommentsController < ApplicationController
  load_and_authorize_resource

  def index
    @comments = Comment.where({ post_id: params[:post_id] }).order('created_at')
    render json: { success: true, data: { comments: @comments } }
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(text: comment_params[:text], user: current_user)

    if @comment.save
      render json: { success: true, data: { comment: @comment } }, status: :created
    else
      render json: { success: false, errors: @comment.errors }, status: :bad_request
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/_posts_controller.rb
class Api::PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.all.order('created_at')
    render json: { success: true, data: { posts: @posts } }
  end
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  load_and_authorize_resource

  def index
    @comments = Comment.where({ post_id: params[:post_id] }).order('created_at')
    render json: { success: true, data: { comments: @comments } }
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(text: comment_params[:text], user: current_user)

    if @comment.save
      render json: { success: true, data: { comment: @comment } }, status: :created
    else
      render json: { success: false, errors: @comment.errors }, status: :bad_request
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.all.order('created_at')
    render json: { success: true, data: { posts: @posts } }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    post = Post.find(params[:post_id])
    comment = post.comments.new(text: comment_params[:text], user: current_user)

    if comment.save
      flash[:notice] = 'Comment added!'
    else
      flash[:alert] = 'Failed to add comment!'
    end
    redirect_to user_post_path(post.user.id, post.id)
  end

  def destroy
    comment = Comment.find params[:id]
    post = comment.post

    if comment.destroy
      flash[:notice] = 'Comment removed!'
    else
      flash[:alert] = 'Failed to remove comment!'
    end
    redirect_to user_post_path(post.user.id, post.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find params[:post_id]
    like = post.likes.new user: current_user

    flash[:alert] = 'Failed to like post!' unless like.save
    redirect_to user_post_path(post.user.id, post.id)
  end

  def destroy
    post = Post.find params[:id]

    flash[:alert] = 'Failed to unlike post!' unless post.users.delete current_user
    redirect_to user_post_path(post.user.id, post.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource only: :all_posts

  def index
    @user = User.find params[:user_id]
    @posts = @user.posts.order(created_at: :desc)
  end

  def show
    @user = User.find params[:user_id]
    @post = @user.posts.includes(:comments).find(params[:id])
    @comments = @post.comments.all.order('created_at')
    @liked = @post.liked? current_user.id
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]

    if @post.update post_params
      redirect_to user_post_path(@post.user.id, @post.id), notice: 'Published successfully!'
    else
      render :new
    end
  end

  def create
    @post = current_user.posts.new post_params

    if @post.save
      redirect_to user_post_path(@post.user.id, @post.id), notice: 'Published successfully!'
    else
      render :new
    end
  end

  def destroy
    post = Post.find params[:id]
    user = post.user

    if post.destroy
      flash[:notice] = 'Post deleted'
    else
      flash[:alert] = 'Failed to delete post!'
    end
    redirect_to user_path(user.id)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order('created_at')
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_photo(user)
    user.photo.present? ? user.photo : "https://ui-avatars.com/api/?name=#{user.name}&background=random"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-navbar-fixed-top">
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <div class="section">
      <div class="container">
        <% if alert.present? %>
          <div class="notification is-danger is-light">
            <button class="delete"></button>
            <%= alert %>
          </div>
        <% end %>
        <% if notice.present? %>
          <div class="notification is-link is-light">
            <button class="delete"></button>
            <%= notice %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_comment.html.erb
<article class="media">
  <figure class="media-left">
    <p class="image is-32x32">
      <%= image_tag(get_photo(comment.user), alt: "avatar", class: "is-rounded") %>
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= comment.user.name %></strong> <small><%= t('time_ago', time: time_ago_in_words(comment.created_at)) %></small>
        <br>
        <%= comment.text %>
      </p>
    </div>
    <% if can? :destroy, comment %>
      <nav class="level is-mobile">
        <div class="level-left"></div>
        <div class="level-right">
		      <%= button_to "Delete", comment_path(comment.id), remote: true, data: { confirm: 'Are you sure?' }, method: :delete, class: "level-item button is-light is-danger is-small" %>
        </div>
      </nav>
    <% end %>
  </div>
</article>

app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
	<% if @post.errors.any? %>
		<div class="notification mb-2 p-2 has-background-danger-light has-text-danger">
			<h3><%= pluralize(@post.errors.count, "error") %> occured:</h3>
			<ul>
				<% @post.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= form.label :title, t('title'), class: "label" %>
		<%= form.text_field :title, placeholder: t('title'), required: true, autofocus: true, class: "input" %>
	</div>
	<div class="field">
		<%= form.text_area :text, placeholder: t('type_here'), rows: 10, required: true, class: "textarea" %>
	</div>
	<%= form.submit t('publish'), class: "button is-link is-success", data: { disable_with: t('loading') } %>
<% end %>

app/views/posts/_header.html.erb
<div class="is-flex mb-2 is-justify-content-flex-end">
	<div class="buttons">
		<% if @liked %>
			<%= button_to pluralize(@post.likes_counter, "Like"), like_path(@post.id), method: :delete, remote: true, class: "button is-primary is-small", data: { disable_with: true } %>
		<% else %>
			<%= button_to pluralize(@post.likes_counter, "Like"), post_likes_path(@post.id), method: :post, remote: true, class: "button is-primary is-small is-inverted", data: { disable_with: true } %>
		<% end %>
		<span class="button is-small is-info is-light is-inverted is-static"><%= pluralize(@post.comments_counter, t('comment')) %></span>
  	<% if can? :edit, @post %>
			<%= link_to t('edit'), edit_post_path(@post.id), class: "button is-light is-link is-small" %>
		<% end %>
		<% if can? :destroy, @post %>
			<%= button_to t('delete'), post_path(@post.id), remote: true, method: :delete, data: { confirm: t('confirm') }, class: "button is-light is-danger is-small" %>
		<% end %>
	</div>
</div>

app/views/posts/_new_comment.html.erb
<%= form_with url: post_comments_path(@post.id), local: false, scope: :comment, class: "mb-6" do |form| %>
	<div class="field">
		<%= form.text_area :text, placeholder: t('leave_comment'), rows: 3, required: true, class: "textarea has-fixed-size" %>
	</div>
	<%= form.submit t('submit'), class: "button is-link", data: { disable_with: t('loading')} %>
<% end %>

app/views/posts/_post.html.erb
<article class="post notification my-2">
  <div class="mb-2">
    <p><%= t('post_id', id: post.id)%></p>
    <p class="is-size-7 is-italic"><%= t('posted_on', date: post.created_at.to_s(:nice_date)) %></p>
  </div>
  <%= link_to user_post_path(post.user.id, post.id), id: post.id do %>
    <h3 class="title mb-2"><%= post.title %></h3>
  <% end %>
  <% if post.text.present? %>
    <p><%= post.text.slice(0, 100) %>...</p>
  <% end %>
  <div class="buttons is-flex is-justify-content-flex-end">
    <span class="button is-small is-light is-transparent is-static"><%= pluralize(post.comments_counter, t('comment')) %></span>
    <span class="button is-small is-light is-transparent is-static"><%= pluralize(post.likes_counter, t('like')) %></span>
  </div>
</article>

app/views/posts/edit.html.erb
<h1 class="title is-4"><%= t('edit_title') %></h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render partial: "users/user", object: @user %>
<div class="columns is-flex-direction-column">
  <% @posts.each do |post| %>
    <div class="column">
      <%= render partial: "post", object: post %>
      <%= render partial: "shared/comment", collection: post.recent_comments %>
    </div>
  <% end %>
</div>
<div id="pagination"></div>

app/views/posts/new.html.erb
<h1 class="title is-4"><%= t('create_title') %></h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= render "header", post: @post %>
<div class="is-flex is-flex-direction-row is-justify-content-space-between is-flex-wrap-wrap my-3">
  <div class="media is-flex is-align-items-center">
    <div class="media-left">
      <div class="image is-32x32">
        <%= image_tag(get_photo(@user), alt: "avatar", class: "is-rounded") %>
      </div>
    </div>
    <div class="media-content">
      <div class="content">
        <strong><%= @user.name %></strong>
        <p class="is-size-7 is-italic"><%= t('posted_on', date: @post.created_at.to_s(:nice_date)) %></p>
      </div>
    </div>
  </div>
</div>
<div class="content">
  <h1><%= @post.title %></h1>
  <p><%= @post.text %></p>
</div>
<%= render partial: "new_comment", post: @post %>
<%= render partial: "comment", collection: @comments %>

app/views/shared/_comment.html.erb
<article class="media">
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= comment.user.name %></strong> <small><%= t('time_ago', time: time_ago_in_words(comment.created_at)) %></small>
        <br>
        <%= comment.text %>
      </p>
    </div>
  </div>
</article>

app/views/shared/_navbar.html.erb
<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
			<h4 class="title is-5"><%= t('brand') %></h4>
    </a>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
  		<% if user_signed_in? %>
        <div class="navbar-item">
          <div class="buttons">
            <%= link_to current_user.name, user_path(current_user.id), class: "button is-info is-small is-inverted" %>
            <%= link_to t('create_post'), new_post_path, class: "button is-link is-small" %>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "button is-small is-danger" %>
          </div>
        </div>
			<% end %>
    </div>
  </div>
</nav>

app/views/users/_user.html.erb
<article class="user media is-align-items-center is-flex-wrap-wrap">
  <div class="media-left">
    <figure class="image is-128x128">
      <%= image_tag(get_photo(user), alt: "avatar", class: 'user-avatar') %>
    </figure>
  </div>
  <div class="media-content notification">
    <div class="content">
      <h4 class="title is-4"><%= user.name %></h4>
      <p class="subtitle is-size-7"><%= t('joined', date: user.created_at.to_s(:nice_date)) %></p>
      <p class="has-text-right is-size-7"><%= pluralize(user.posts_counter, t('post')) %></p>
    </div>
  </div>
</article>

app/views/users/index.html.erb
<div class="columns is-flex-direction-column">
  <% @users.each do |user| %>
    <%= link_to user_path(user.id), class: "column", id: user.id do %>
      <%= render partial: "user", object: user %>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<%= render @user %>
<% if @user.bio.present? %>
	<div class="mt-5 notification">
	  <h5 class="title is-6">Bio</h5>
	  <p class="is-6"><%= @user.bio %></p>
	</div>
<% end %>
<%= render partial: "posts/post", collection: @posts %>
<% if @user.posts_counter > 0 %>
	<%= link_to "See all post", user_posts_path(@user.id), class: "button is-link is-small" %>
<% end %>